### ISSUE TITLE
Request for info

### ISSUE THREAD

**Issue by robmarkcole** [jbshep/flask-image-demo#2]
Hi
I am interested in getting this running, and am wondering if you ever produced documentation for the class? I need to setup the database and add some data for example.
Thanks in advance
Robin

**Comment by jbshep** [comment]
Hi, @robmarkcole.  Thanks for your interest.  The only documentation produced for the class is the README.md file.  The intended audience for this project was a Web app development class of mine, and prior to experiencing this example, the students already had a good understanding of how to build a Flask app and how to install PostgreSQL.  Thus, I did not include instructions on how to install PostgreSQL.  I did (in the README.md file) direct them to create the named database prior to launching the app for the first time.  Any new images can be uploaded using the Web form to which you can navigate from http://localhost:5000/.

Is there a particular step or paragraph in the README.md that needs additional clarification?   Again, thanks for your interest.

**Comment by robmarkcole** [comment]
I wasn't sure if the databasee schema mattered? A couple of screenshots would be nice to see also.
Thanks!

**Comment by jbshep** [comment]
The database schema is created using the command found near the end of the README.md file (which I've pasted below).

```
python3 manage.py db upgrade
```

That command uses the DB migrations scripts found in the `migrations` folder to update the schema of the empty database that you created in an earlier step (by using `psql` and entering `create database imagedemo;`).  If you haven't used migrations before, they are a great way to update the database schema in a way that synchronizes with your code changes.

**Comment by jbshep** [comment]
I think a big part of the ambiguity in the README.md file is due to the intended audience.  I pushed this project to GitHub as a reference for the students in my class who have already (at this point in the class) built Flask apps that talk to a PostgreSQL back-end and used migrations to manage changes to the schema.  Perhaps in the future I could make this project into a tutorial for a more general audience (and perhaps there could even be an accompanying blog post).  I teach this course again in the upcoming spring semester, so it's possible I could do so.

**Comment by robmarkcole** [comment]
Thanks for the instructions and advice on `migrations`. I've found many useful articles on Medium, which can embed code from Github repos, so that might be a nice way to go.
Thanks again
